### ISSUE TITLE
Doesn't work when the file location has space

### ISSUE THREAD

**Issue by FuturisticGoo** [SegoCode/AutoWall#1]
When the file location has spaces in between it doesn't apply the wallpaper.

**Comment by SegoCode** [comment]
Hey,
I try to reproduce the issue, can you give me more information about? is reproducible only on the "Apply" button?
In my tests works fine using "Browse" and "Apply" button.

![Test](https://user-images.githubusercontent.com/35817798/94295487-9a11f480-ff61-11ea-83e0-068457b14b49.png)

**Comment by FuturisticGoo** [comment]
Hmm, yes now it works. For some reason yesterday it didn't work when there was space in the file location. Sorry about that. I'll close the issue
