### ISSUE TITLE
black frame

### ISSUE THREAD

**Issue by KaninchenSpeed** [SegoCode/AutoWall#11]
theres one black frame when the video restarts.

**Comment by SegoCode** [comment]
hi !
Can you tell me if it is related or similar to this #4 ?

**Comment by KaninchenSpeed** [comment]
I dont see a border. Its just one black frame when the video restarts.

**Comment by SegoCode** [comment]
Do you mean... the aspect ratio of the video makes appears black bands? Can you attach screenshots pls?

**Comment by KaninchenSpeed** [comment]
I cant screenshot it because its just one frame long. Its just as if the video has one black frame at the end

**Comment by SegoCode** [comment]
But... the loop video contains a black frame? well, autowall doesnt modify the video file, if the video doesnt fit your screen or the loop isnt correct, please try other videos... Autowall is only a video player like VLC but behind the desktop icons...

You can downloads from steam Workshop or livewallpaper pages in google...

**Comment by KaninchenSpeed** [comment]
I found out that this problem only appears when using mp4s. Gifs work fine

**Comment by SegoCode** [comment]
Can you [upload](https://upload.disroot.org/) or attach the mp4s file?
