### ISSUE TITLE
Live wallpaper lost if Windows gets locked

### ISSUE THREAD

**Issue by ToddPerkins81** [SegoCode/AutoWall#18]
I noticed that the app works fine for turning mp4 files into live wallpaper, but when I lock the computer (Like with Win key + L), the desktop then goes back to whatever it was set to before the live wallpaper.  I also tried ticking the -Set on windows startup option but it still does it.

I'm pretty new to Windows live wallpapers so I don't really know much about possible limitations for this kind of thing.

**Comment by SegoCode** [comment]
I work well with my computer, Win + L doesnt remove the wallpaper live.
What windows version are you using? Are you blocking the PC with Win + L or maybe this is entering Hibernation? Maybe some optimization program is closing autowall?

**Comment by ToddPerkins81** [comment]
I'm running Windows 10 Home OS build 19043.1165
I have my computers set up to skip the lock screen and just go straight to the password entry.  My PC is set to not go to sleep or hibernate.  I thought it may be because I have my desktop (Through the Windows settings) to do a slideshow instead of a single static image, however I was not able to reproduce this issue on a different computer that I have.  

If I reboot the PC, it still comes back on, it's just Win + L to lock it, and only on one of my computers.  Autowall is still running in the system tray as well as the UI box if I leave it up.

**Comment by SegoCode** [comment]
Looks an issue from [weebp](https://github.com/Francesco149/weebp)... the core behind AutoWall right now I can't do anything about it but i plan to make my own core at some point

**Comment by SegoCode** [comment]
The new version has improvements about it https://github.com/SegoCode/AutoWall/releases/tag/1.10
