### ISSUE TITLE
Multi screens not available

### ISSUE THREAD

**Issue by byrod** [SegoCode/AutoWall#2]
When setting a gif wallpaper, in dual screens setup, le wallpaper in showing in the middle of the two screens :D

**Comment by SegoCode** [comment]
Hi, 
I know that limitation, reading the [weebp repo](https://github.com/Francesco149/weebp/issues/2) there are some parameters to support dual screens, but right now I can't test it. 😔
Maybe will be added for future new version.

Any way, if you want, try to download the AutoWall.au3 file and editing the run() method in setwallpaper() function, after this you can compile it with [Aut2exe portable.](https://www.autoitscript.com/cgi-bin/getfile.pl?autoit3/autoit-v3.zip) 👏

**Comment by lsyk4** [comment]
Same issue here
The tool is awesome.
Waiting for an update where you enable multi screen :D

**Comment by SegoCode** [comment]
Hey, check new release, in case of having two screens the wallpaper will be adjusted to the first one

**Comment by lsyk4** [comment]
When I run the new version, Antivirus takes it as a threat

**Comment by rokmc820** [comment]
Thanks to the SegoCode, I am using it very easily and comfortably.
Thank you. I hope multi-monitor will be supported in the next version.
You will be blessed.

**Comment by fire** [comment]
Do you have a design for how to add this?

I can try looking.

**Comment by SegoCode** [comment]
@fire 
I dont know any idea how to implement, also i have only one monitor, so i cant tested it.

My first approach was reading the [doc for weebp and mpv](https://github.com/Francesco149/weebp#rationale-and-how-it-works) but couldnt test it, I left it pending

**Comment by SegoCode** [comment]
Good news guys,
Im working right now in multi screen, a lot of work to do, but i finally set a different live wallpapers on different screens simultaneously 👏

![multiscreen](https://user-images.githubusercontent.com/35817798/156033357-2466ec20-42d8-4ab6-9acf-e1a756e9ec79.png)

**Comment by fire** [comment]
How can I get this version to provide feedback?

**Comment by SegoCode** [comment]
Hi @fire thanks for the interest to help the repo, at this point the only way to try this version is compiling https://github.com/SegoCode/AutoWall/blob/master/src/AutoWall.au3 I have been uploading the changes, if you want I can provide you the binaries of last commit, In any case contact to me, my email is available on my github profile 💕

**Comment by fire** [comment]
Sorry, I wasn't able to test. So I'll wait a official release.

**Comment by SegoCode** [comment]
Guys the new version is available https://github.com/SegoCode/AutoWall/releases with support for different screens in beta, I'm going to close this issue, any bug or something to improved on this topic, please open an new issue. https://github.com/SegoCode/AutoWall#multiple-screens

Thanks all for the support 💕
