### ISSUE TITLE
Blocks Windows from Sleeping

### ISSUE THREAD

**Issue by AkazaRenn** [SegoCode/AutoWall#20]
```
PS C:\Users\i> powercfg /requests
DISPLAY:
[PROCESS] \Device\HarddiskVolume3\Users\i\Downloads\AutoWall\AutoWall\mpv\mpv.exe

SYSTEM:
[PROCESS] \Device\HarddiskVolume3\Users\i\Downloads\AutoWall\AutoWall\mpv\mpv.exe

AWAYMODE:
None.

EXECUTION:
None.

PERFBOOST:
None.

ACTIVELOCKSCREEN:
None.
```

**Comment by SegoCode** [comment]
Hmmm interesting, I found information about it, I will investigate it thoroughly for the next version 

maybe ```powercfg /requestsoverride /? ``` can help for this

https://superuser.com/questions/561381/where-are-changes-made-by-the-pwrcfg-exe-command-line-utility-stored
https://superuser.com/questions/1181186/power-request-types-whats-the-difference-between-display-system-awaymode-p
https://github.com/mpv-player/mpv/issues/1841

**Comment by rocksdanister** [comment]
Just set `--stop-screensaver=no` mpv flag.

**Comment by SegoCode** [comment]
> stop-screensaver=no

@AkazaRenn can you try add this in the conf file https://github.com/SegoCode/AutoWall/blob/master/src/mpv/mpv.conf

Confirm that fixes the problem pls

Thxxx!

**Comment by AkazaRenn** [comment]
@SegoCode sorry wasn't checking GitHub recently, just tested and seems perfect. Thank you and @rocksdanister !
![image](https://user-images.githubusercontent.com/8340896/155994634-a8eb0e37-2d6c-4d4c-acf3-82aa0573e1ca.png)

**Comment by SegoCode** [comment]
Nice! commited,
Thank all for helping 💕
