### ISSUE TITLE
Compiling

### ISSUE THREAD

**Issue by tytoppik** [SegoCode/AutoWall#21]
How to compile a project from source?

**Comment by SegoCode** [comment]
Hi, 

Easy, here you have a few steps to start:

First of all download the repository ```git clone https://github.com/SegoCode/AutoWall```

Now download the [mpv](https://mpv.io/installation/) and [weebp](https://github.com/Francesco149/weebp/releases) binary and unzip to respectives folders ```AutoWall/src/weebp``` and ```AutoWall/src/mpv```

Using [Aut2Exe](https://www.autoitscript.com/autoit3/docs/intro/compiler.htm) available [here](https://www.autoitscript.com/cgi-bin/getfile.pl?autoit3/autoit-v3.zip) compile to x64 Autowall.au3 and keep binary in the actual .au3 folder

At this point you can use AutoWall running Autowall.exe , but some extra functions will not be available, for that remains you will have to [download and install golang](https://go.dev/doc/install) using ```golang build``` compile all .go files in ```AutoWall/src/tools``` the last file is AutoPause.au, use Aut2Exe, and keep binary in ```AutoWall/src/tools``` also check this https://github.com/SegoCode/AutoWall/issues/19#issuecomment-955776642

**Comment by tytoppik** [comment]
Thanks for the answer) I will try

**Comment by SegoCode** [comment]
Keep in mind, Autowall its only a script to coordinate mpv and weebp, it has no dependence with ```AutoWall/src/tools``` , and all the extra files the only thing that do Autowall is running a binary called *.exe at some point

**Comment by SegoCode** [comment]
I think about it....
I'm going to start working on compiling guide, explaining the code and functionality, to make it easier for others to contribute.

**Comment by SegoCode** [comment]
I think the compilation guide is well done, if you need any improvement, please let me know.
