### ISSUE TITLE
[BUG REPORT] - W11 24H2

### ISSUE THREAD

**Issue by nazzy121** [SegoCode/AutoWall#36]
### Description

Hi, looks like this app is broken on W11 24H2.  Video plays on top of desktop icons.   Is there any plan to update Autowall to be compatible with 24H2? 

### Steps to reproduce

Play any video in Autowall

### Expected behavior

Video should play behind desktop icons

### Actual behavior

Video plays on top of desktop icons

### Windows version

Windows 11

### Confirmation

- [X] I performed a [search of the issue tracker](https://github.com/segocode/AutoWall/issues) to avoid opening a duplicate issue
- [X] I understand that not filling out this template correctly may lead to the issue being closed

**Comment by SegoCode** [comment]
Yes, quite frustrating that it has stopped working, I am not the maintainer of the core of the application, which is [weebp](https://github.com/Francesco149/weebp). So for now it won't work until I try coding my own core

**Comment by SegoCode** [comment]
Working on it https://github.com/SegoCode/AutoWall/commit/6c4fea705102b8556e5f0e3e60048ef8d9f5f666

**Comment by SegoCode** [comment]
Fixed in [1.13](https://github.com/SegoCode/AutoWall/releases/tag/1.13)
