### ISSUE TITLE
No Startup cmd Window, Please.

### ISSUE THREAD

**Issue by criticalsoft** [SegoCode/AutoWall#7]

**Comment by SegoCode** [comment]
Autowall creates a batch in `%APPDATA%\Microsoft\Windows\Start Menu\Programs\Startup\` for run weebp, easy edit and modify, non-intrusive exe in background.

**Comment by criticalsoft** [comment]
OK, Thank You.

**Comment by SegoCode** [comment]
I had an idea, the next updates will come with changes related to this issue

**Comment by SegoCode** [comment]
Feature implemented in 1.6
