### ISSUE TITLE
I cannot find the app

### ISSUE THREAD

**Issue by jennnnnnnnnnnnnnn** [SegoCode/AutoWall#8]
When I download the zip carpet, there is no .exe file inside!

**Comment by SegoCode** [comment]
Hi Jen, I checked the release and everything is OK, check that your antivirus maybe delete it. We have issues about that #3

![Captura](https://user-images.githubusercontent.com/35817798/114474307-3c3fb400-9bf6-11eb-94ea-bf217b36975f.PNG)

Tell me when you have news about. 👌
